// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewPreference struct {
	Description string `json:"description"`
}

type Preference struct {
	ID          string  `json:"id"`
	Description string  `json:"description"`
	VideoURL    *string `json:"videoUrl"`
}
